package expo.modules.macros.processor

/**
 * Turns a [ModuleModel] into the text of the generated `<Module>.expoModuleDefinition()` extension.
 *
 * The output builds the module's `ModuleDefinitionData` with the existing `ModuleDefinition { … }`
 * DSL, so it compiles against today's `expo-modules-core` with no core changes — the author opts in
 * by returning it from `definition()`. This mirrors what the Swift `@ExpoModule` macro synthesizes,
 * the difference being that KSP emits a separate extension instead of adding a member to the class.
 *
 * Pure string building with no KSP dependency, so it is unit-testable on its own.
 */
internal object DefinitionGenerator {
  /**
   * The lambda passed to `ModuleDefinition { … }` runs with `ModuleDefinitionBuilder` as its
   * receiver, so a bare `greet(…)` would resolve against the builder, not the module. Every call
   * back into the module is qualified with this label, which names the enclosing extension's `this`.
   */
  private const val RECEIVER = "this@expoModuleDefinition"

  fun generate(model: ModuleModel): String {
    val body = buildString {
      appendLine("  Name(\"${model.jsName}\")")
      for (function in model.functions) {
        appendLine("  " + functionEntry(function))
      }
      for (property in model.properties) {
        appendLine("  " + propertyEntry(property))
      }
    }.trimEnd('\n')

    return buildString {
      appendLine("// Generated by expo-modules-macros. Do not edit.")
      appendLine("package ${model.packageName}")
      appendLine()
      appendLine("import expo.modules.kotlin.functions.Coroutine")
      appendLine("import expo.modules.kotlin.modules.ModuleDefinition")
      appendLine("import expo.modules.kotlin.modules.ModuleDefinitionData")
      appendLine()
      appendLine("internal fun ${model.simpleName}.expoModuleDefinition(): ModuleDefinitionData = ModuleDefinition {")
      append(body)
      appendLine()
      appendLine("}")
    }
  }

  /**
   * A sync `@JS fun` becomes `Function("name") { p0: T -> receiver.fn(p0) }`; a `suspend fun` becomes
   * `AsyncFunction("name") Coroutine { p0: T -> receiver.fn(p0) }` (a JS Promise). The lambda
   * parameters carry explicit types because the DSL infers each argument's converter from them.
   */
  private fun functionEntry(function: FunctionModel): String {
    val params = function.parameters.joinToString(", ") { "${it.name}: ${it.type}" }
    val lambdaHeader = if (function.parameters.isEmpty()) "->" else "$params ->"
    val args = function.parameters.joinToString(", ") { it.name }
    val call = "$RECEIVER.${function.kotlinName}($args)"
    return if (function.isSuspend) {
      "AsyncFunction(\"${function.jsName}\") Coroutine { $lambdaHeader $call }"
    } else {
      "Function(\"${function.jsName}\") { $lambdaHeader $call }"
    }
  }

  /**
   * A `@JS val` becomes `Property("name").get { receiver.p }`; a `@JS var` additionally gets
   * `.set { value: T -> receiver.p = value }`. The setter's value type is spelled explicitly so the
   * builder's reified `set` resolves the converter, the same reason function lambdas are typed.
   */
  private fun propertyEntry(property: PropertyModel): String {
    val getter = "Property(\"${property.jsName}\").get { $RECEIVER.${property.kotlinName} }"
    if (!property.isMutable) {
      return getter
    }
    return "$getter.set { value: ${property.type} -> $RECEIVER.${property.kotlinName} = value }"
  }
}
