package expo.modules.macros.processor

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Unit tests over [DefinitionGenerator] alone (no compiler) — fast, exact assertions on the
 * generated text. The end-to-end "does it actually compile" check lives in
 * [ExpoModuleProcessorTest].
 */
class DefinitionGeneratorTest {
  private fun model(
    functions: List<FunctionModel> = emptyList(),
    properties: List<PropertyModel> = emptyList(),
    jsName: String = "MyModule"
  ) = ModuleModel(
    qualifiedName = "com.example.MyModule",
    packageName = "com.example",
    simpleName = "MyModule",
    jsName = jsName,
    functions = functions,
    properties = properties
  )

  @Test
  fun `emits package, imports and the extension signature`() {
    val source = DefinitionGenerator.generate(model())
    assertTrue(source.contains("package com.example"), source)
    assertTrue(source.contains("import expo.modules.kotlin.modules.ModuleDefinition"), source)
    assertTrue(
      source.contains("internal fun MyModule.expoModuleDefinition(): ModuleDefinitionData = ModuleDefinition {"),
      source
    )
    assertTrue(source.contains("Name(\"MyModule\")"), source)
  }

  @Test
  fun `uses the JS module name for Name`() {
    val source = DefinitionGenerator.generate(model(jsName = "CustomName"))
    assertTrue(source.contains("Name(\"CustomName\")"), source)
  }

  @Test
  fun `sync function with no args`() {
    val source = DefinitionGenerator.generate(
      model(functions = listOf(FunctionModel("reset", "reset", emptyList(), isSuspend = false)))
    )
    assertTrue(
      source.contains("Function(\"reset\") { -> this@expoModuleDefinition.reset() }"),
      source
    )
  }

  @Test
  fun `sync function with typed args forwards by name`() {
    val source = DefinitionGenerator.generate(
      model(
        functions = listOf(
          FunctionModel(
            kotlinName = "greet",
            jsName = "greet",
            parameters = listOf(
              ParameterModel("name", "kotlin.String"),
              ParameterModel("times", "kotlin.Int")
            ),
            isSuspend = false
          )
        )
      )
    )
    assertTrue(
      source.contains(
        "Function(\"greet\") { name: kotlin.String, times: kotlin.Int -> this@expoModuleDefinition.greet(name, times) }"
      ),
      source
    )
  }

  @Test
  fun `suspend function becomes AsyncFunction Coroutine`() {
    val source = DefinitionGenerator.generate(
      model(
        functions = listOf(
          FunctionModel(
            kotlinName = "work",
            jsName = "work",
            parameters = listOf(ParameterModel("id", "kotlin.String")),
            isSuspend = true
          )
        )
      )
    )
    assertTrue(
      source.contains(
        "AsyncFunction(\"work\") Coroutine { id: kotlin.String -> this@expoModuleDefinition.work(id) }"
      ),
      source
    )
  }

  @Test
  fun `read-only property emits a getter only`() {
    val source = DefinitionGenerator.generate(
      model(properties = listOf(PropertyModel("version", "version", "kotlin.String", isMutable = false)))
    )
    assertTrue(
      source.contains("Property(\"version\").get { this@expoModuleDefinition.version }"),
      source
    )
    assertFalse(source.contains(".set"), source)
  }

  @Test
  fun `mutable property emits getter and typed setter`() {
    val source = DefinitionGenerator.generate(
      model(properties = listOf(PropertyModel("ready", "ready", "kotlin.Boolean", isMutable = true)))
    )
    assertTrue(
      source.contains(
        "Property(\"ready\").get { this@expoModuleDefinition.ready }.set { value: kotlin.Boolean -> this@expoModuleDefinition.ready = value }"
      ),
      source
    )
  }

  @Test
  fun `JS name override is used for the wire name but the kotlin name for the call`() {
    val source = DefinitionGenerator.generate(
      model(
        functions = listOf(
          FunctionModel("performWork", "doWork", emptyList(), isSuspend = false)
        )
      )
    )
    assertTrue(
      source.contains("Function(\"doWork\") { -> this@expoModuleDefinition.performWork() }"),
      source
    )
  }

  @Test
  fun `empty module still produces a valid definition`() {
    val source = DefinitionGenerator.generate(model())
    val expected = """
      |// Generated by expo-modules-macros. Do not edit.
      |package com.example
      |
      |import expo.modules.kotlin.functions.Coroutine
      |import expo.modules.kotlin.modules.ModuleDefinition
      |import expo.modules.kotlin.modules.ModuleDefinitionData
      |
      |internal fun MyModule.expoModuleDefinition(): ModuleDefinitionData = ModuleDefinition {
      |  Name("MyModule")
      |}
    """.trimMargin() + "\n"
    assertEquals(expected, source)
  }
}
