// The Android counterpart of the Swift macros in `apple/`. Instead of compiler macros,
// the JS surface is generated by a KSP (Kotlin Symbol Processing) processor: `:annotations`
// holds the markers an author applies (`@ExpoModule`, `@JS`), and `:processor` reads them and
// generates the module definition.
//
// Kotlin/KSP are pinned independently of `expo-modules-core` (which builds with Kotlin 2.0.21):
// this is a standalone tool whose only contract with core is that the *generated* code compiles
// against core's DSL, not that it shares a compiler version. 2.1.20 is chosen because it (and its
// matching KSP `2.1.20-2.0.1`) resolves from the local Gradle cache.

plugins {
  kotlin("jvm") version "2.1.20" apply false
  id("com.google.devtools.ksp") version "2.1.20-2.0.1" apply false
}

subprojects {
  repositories {
    mavenCentral()
    google()
  }
}
